### ISSUE TITLE
Allow transparency in renderer?

### ISSUE THREAD

**Issue by IzMichael** [bs-community/skinview3d#129]
Hiya, I'm trying to only render portions of a skin, so the `skin.png` that I'm giving the renderer only contains the torso. Unfortunately, the 3d renderer is showing the missing parts as an opaque black.

![image](https://user-images.githubusercontent.com/57115702/212197863-6dbeb0e1-520f-4060-bc8d-e85f23bbd0ff.png)

Is there a way for me to make the missing parts of a skin just be transparent?
Thanks!

**Comment by Hacksore** [comment]
That's because we never let the first layer be transparent as the game will render your skin black in transparent areas.

https://github.com/bs-community/skinview3d/blob/256b18918a732c893fa422bfcae640110ff5708d/src/model.ts#L75-L77

You can programmatically disable body parts to achieve what you are looking for though.

**Comment by IzMichael** [comment]
Ah, right - Ty!
