### ISSUE TITLE
Add a callback to get latest zoom value

### ISSUE THREAD

**Issue by so1ve** [bs-community/skinview3d#136]
Like:

```ts
viewer.onZoom((newZoom) => {/* ... */})
```

**Comment by Hacksore** [comment]
Gotcha! Here is some helpful reference material since three uses its own emitter.

https://threejs.org/docs/#examples/en/controls/OrbitControls
https://github.com/mrdoob/three.js/blob/master/examples/jsm/controls/OrbitControls.js#LL2C2-L2C17
https://github.com/mrdoob/three.js/blob/master/src/core/EventDispatcher.js
https://threejs.org/docs/#api/en/core/EventDispatcher

I was able to add this code in `viewer.ts` to see events.
```ts
this.controls.addEventListener("change", (event) => {
  console.log(event);
})
```

**Comment by so1ve** [comment]
Damn it, I can't find a way to get the latest value...

**Comment by Hacksore** [comment]
@so1ve maybe you can file an upstream issue to threejs to see if they have ideas.

**Comment by Hacksore** [comment]
@so1ve can you please reopen a new issue once there is any upstream support for this?
