### ISSUE TITLE
Optimizing WebGL contexts

### ISSUE THREAD

**Issue by MrZillaGold** [bs-community/skinview3d#72]
At the moment, when using a large number of skinview3d instances, we will get the error: `Too many active WebGL contexts. Oldest context will be lost`.
![image](https://user-images.githubusercontent.com/42776347/91400587-438e9900-e883-11ea-8e01-c7b0053cddbf.png)

Is there a way to optimize the WebGL contexts on the library side?

**Comment by yushijinhun** [comment]
Why do you need so many skinview3d instances? Is it possible to reuse them?

**Comment by MrZillaGold** [comment]
I'm doing something like a gallery of skins, the only solution to which I have come to use images instead of skinview3d, and already by clicking on a skin it will be possible to examine it in detail with skinview3d.

Although I partly no longer depend on it, sooner or later others will need it.

**Comment by Hacksore** [comment]
Using this library for a gallery just doesn't seem practical due to the browser limiting the max WebGL contexts. The best approach would be using a 2d library (https://github.com/bs-community/skinview2d needs some help) then when clicking/hovering it you could swap it out for a 3d renderer.

Attempt to load 20 renderers: https://codesandbox.io/s/skinview3d-example-many-renderers-locij?file=/src/index.js
![image](https://user-images.githubusercontent.com/996134/91856104-b7d28f00-ec2b-11ea-858a-d44fb0450688.png)

I'm going to close this out as to me it's more about how you plan to implement with the lib.

**Comment by yushijinhun** [comment]
@MrZillaGold  If you need static skin previews (without animation or interaction), it is unnecessary to create multiple skinview3d instances. You can render the player to a canvas which is not attached to the document, and then take a screenshot using `.toDataURL()`.

But currently it's a bit inconvenient because skinview3d automatically attaches the canvas to the document. This problem will be solved in #73.

**Comment by yushijinhun** [comment]
I added a new example to show how to generate static previews (by taking screenshots). [source](https://github.com/bs-community/skinview3d/blob/master/examples/offscreen-render.html); [demo](https://bs-community.github.io/skinview3d/offscreen-render.html);
