### ISSUE TITLE
Cape from link isn't working

### ISSUE THREAD

**Issue by 2yf** [bs-community/skinview3d#80]
If i upload cape normally it works, but if i'm trying to load it from link (ie. imgur (with .png added) it doesn't work

How can I make it to work properly?

(sorry for my english man)

**Comment by Hacksore** [comment]
@2yf Seems working for me on a codesandbox but I did notice that Imgur was throwing 403's trying to serve from `127.0.0.1`. 

If you are developing locally and trying to load an externally referenced Imgur URL access your local from `localhost` it seemed to work for me which means Imgur but has some reason to block 127.0.0.1 requests.

https://codesandbox.io/s/skinview3d-example-imgur-zji2e?file=/src/index.js

Since this is an issue with a third-party site anyway I'm going to close this issue but hope this helps you nevertheless.
