### ISSUE TITLE
Make it so you can right click and open the context menu and save image like namemc's skin viewer

### ISSUE THREAD

**Issue by withdrew** [bs-community/skinview3d#91]
the title ^

**Comment by Hacksore** [comment]
This sounds like you should implement that behavior in your application as I don't feel it's a library deliverable.

**Comment by Hacksore** [comment]
Actually, I see what you mean @withdrew 

![image](https://user-images.githubusercontent.com/996134/129968890-0da9369b-d4b1-4315-9702-85f3a9cfce13.png)

**Comment by withdrew** [comment]
yeah thats what im trying to replicate it works with normal canvases but for some reason the skinview3d canvas you can right click on or atleast it doesnt popup the context menu

**Comment by Hacksore** [comment]
It's mainly caused by this listener being added from the orbit controls.

https://github.com/mrdoob/three.js/blob/44b8fa7b452dd0d291b9b930fdfc5721cb6ebee9/examples/jsm/controls/OrbitControls.js#L1253

Here is an example of how this can be done but just canceling the event propagation.

https://codesandbox.io/s/skinview3d-context-menu-example-hqqbg?file=/src/index.js

**Comment by bribes** [comment]
Hey this solution no longer works.
